

 CREATE TABLE  USERTEST
   (ID bigint NOT NULL auto_increment,
	PASSWORD VARCHAR(255),
	ROLE VARCHAR(255),
	USERNAME VARCHAR(255)
   ) engine=MyISAM;


CREATE TABLE  TBL_EMPREVIEW
   (E_ID bigint NOT NULL auto_increment,
	E_ADDRESS VARCHAR(255),
	E_EMAIL VARCHAR(255),
	E_MOBILE VARCHAR(255),
	E_NAME VARCHAR(255),
	E_NUMBER VARCHAR(255),
	E_PASSWORD VARCHAR(255),
	E_ROLE VARCHAR(255),
	E_USERNAME VARCHAR(255)
   ) ;

CREATE TABLE  "TBL_REVIEWMESSAGE"
   (M_ID bigint NOT NULL auto_increment,
	M_FEEDBACK VARCHAR(255),
	M_MESSAGE VARCHAR(255),
	M_REVIEWED VARCHAR(255),
	M_REVIEWING VARCHAR(255)
   ) ;



